/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as StudentsCreateRouteImport } from './routes/students/create'
import { Route as StudentsStudentIdRouteImport } from './routes/students/$studentId'
import { Route as ParentsCreateRouteImport } from './routes/parents/create'
import { Route as ParentsParentIdRouteImport } from './routes/parents/$parentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsCreateRoute = StudentsCreateRouteImport.update({
  id: '/students/create',
  path: '/students/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsCreateRoute = ParentsCreateRouteImport.update({
  id: '/parents/create',
  path: '/parents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentIdRoute = ParentsParentIdRouteImport.update({
  id: '/parents/$parentId',
  path: '/parents/$parentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/parents/create': typeof ParentsCreateRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/create': typeof StudentsCreateRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/parents/create': typeof ParentsCreateRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/create': typeof StudentsCreateRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/parents/create': typeof ParentsCreateRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/create': typeof StudentsCreateRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parents/$parentId'
    | '/parents/create'
    | '/students/$studentId'
    | '/students/create'
    | '/parents'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parents/$parentId'
    | '/parents/create'
    | '/students/$studentId'
    | '/students/create'
    | '/parents'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/parents/$parentId'
    | '/parents/create'
    | '/students/$studentId'
    | '/students/create'
    | '/parents/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentsParentIdRoute: typeof ParentsParentIdRoute
  ParentsCreateRoute: typeof ParentsCreateRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  StudentsCreateRoute: typeof StudentsCreateRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/create': {
      id: '/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof StudentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/create': {
      id: '/parents/create'
      path: '/parents/create'
      fullPath: '/parents/create'
      preLoaderRoute: typeof ParentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/$parentId': {
      id: '/parents/$parentId'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId'
      preLoaderRoute: typeof ParentsParentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentsParentIdRoute: ParentsParentIdRoute,
  ParentsCreateRoute: ParentsCreateRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  StudentsCreateRoute: StudentsCreateRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
